name: Validate FOMOD

on: 
  push:
    paths:
      - 'dist/ModuleConfig.xml'
  workflow-dispatch:  

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Download schema
      run: wget https://github.com/GandaG/fomod-schema/raw/master/ModuleConfig.xsd
    - name: Lint ModuleConfig.xml
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./dist/fomod/info.xml
        xml-schema-file: ./ModuleCongig.xsd
